const Data= [
    {
        image:"https://artprojectsforkids.org/wp-content/uploads/2020/04/Minion.jpg",
        name:"Doremon"
    },
    {
        image:"https://i.ytimg.com/vi/dw0ht6Rt-vI/maxresdefault.jpg",
        name:"Doremon"
    },
    {
        image:"https://i.ytimg.com/vi/ZUCHi_2ncPQ/maxresdefault.jpg",
        name:"Doremon"
    },
    {
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXqg6lB-5FhPjWVwF4rUpAmlrqQIqFxjOGDg&usqp=CAU",
        name:"Doremon"
    },
    {
        image:"https://artprojectsforkids.org/wp-content/uploads/2020/04/Minion.jpg",
        name:"Doremon"
    },
    {
        image:"https://i.ytimg.com/vi/dw0ht6Rt-vI/maxresdefault.jpg",
        name:"Doremon"
    },
    {
        image:"https://i.ytimg.com/vi/ZUCHi_2ncPQ/maxresdefault.jpg",
        name:"Doremon"
    },
    {
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXqg6lB-5FhPjWVwF4rUpAmlrqQIqFxjOGDg&usqp=CAU",
        name:"Doremon"
    },
    {
        image:"https://artprojectsforkids.org/wp-content/uploads/2020/04/Minion.jpg",
        name:"Doremon"
    },
    {
        image:"https://i.ytimg.com/vi/dw0ht6Rt-vI/maxresdefault.jpg",
        name:"Doremon"
    },
    {
        image:"https://i.ytimg.com/vi/ZUCHi_2ncPQ/maxresdefault.jpg",
        name:"Doremon"
    },
    {
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXqg6lB-5FhPjWVwF4rUpAmlrqQIqFxjOGDg&usqp=CAU",
        name:"Doremon"
    }
]
export default Data;